// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../../stitchvault/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "classify:complete": services$0.ClassifyCompleteEvent;
            "classify:error": services$0.ClassifyErrorEvent;
            "classify:progress": services$0.ClassifyProgressEvent;
            "export:complete": services$0.ExportCompleteEvent;
            "export:error": services$0.ExportErrorEvent;
            "export:progress": services$0.ExportProgressEvent;
            "folders:complete": services$0.FoldersCompleteEvent;
            "folders:error": services$0.FoldersErrorEvent;
            "import:complete": services$0.ImportCompleteEvent;
            "import:error": services$0.ImportErrorEvent;
            "import:progress": services$0.ImportProgressEvent;
            "restore:complete": services$0.RestoreCompleteEvent;
            "restore:error": services$0.RestoreErrorEvent;
            "restore:progress": services$0.RestoreProgressEvent;
        }
    }
}
