//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../../../../../stitchvault/services/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "classify:complete": $$createType0,
        "classify:error": $$createType1,
        "classify:progress": $$createType2,
        "import:complete": $$createType3,
        "import:error": $$createType4,
        "import:progress": $$createType5,
    }));
}

// Private type creation functions
const $$createType0 = services$0.ClassifyCompleteEvent.createFrom;
const $$createType1 = services$0.ClassifyErrorEvent.createFrom;
const $$createType2 = services$0.ClassifyProgressEvent.createFrom;
const $$createType3 = services$0.ImportCompleteEvent.createFrom;
const $$createType4 = services$0.ImportErrorEvent.createFrom;
const $$createType5 = services$0.ImportProgressEvent.createFrom;

configure();
