// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Document represents an ingested file.
 */
export class Document {
    /**
     * Creates a new Document instance.
     * @param {Partial<Document>} [$$source = {}] - The source object to create the Document.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * "indexed" | "processing" | "error"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("chunk_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunk_count"] = 0;
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("centroid" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["centroid"] = [];
        }
        if (!("indexed_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["indexed_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Document}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("centroid" in $$parsedSource) {
            $$parsedSource["centroid"] = $$createField8_0($$parsedSource["centroid"]);
        }
        return new Document(/** @type {Partial<Document>} */($$parsedSource));
    }
}

/**
 * DocumentGroup clusters related documents.
 */
export class DocumentGroup {
    /**
     * Creates a new DocumentGroup instance.
     * @param {Partial<DocumentGroup>} [$$source = {}] - The source object to create the DocumentGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("doc_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["doc_ids"] = [];
        }
        if (!("centroid" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["centroid"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("doc_ids" in $$parsedSource) {
            $$parsedSource["doc_ids"] = $$createField2_0($$parsedSource["doc_ids"]);
        }
        if ("centroid" in $$parsedSource) {
            $$parsedSource["centroid"] = $$createField3_0($$parsedSource["centroid"]);
        }
        return new DocumentGroup(/** @type {Partial<DocumentGroup>} */($$parsedSource));
    }
}

/**
 * Session represents a named knowledge base.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("documents" in $$source)) {
            /**
             * @member
             * @type {Document[]}
             */
            this["documents"] = [];
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {DocumentGroup[]}
             */
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField3_0($$parsedSource["documents"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField4_0($$parsedSource["groups"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Document.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = DocumentGroup.createFrom;
const $$createType5 = $Create.Array($$createType4);
