// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CatalogService is the Wails-facing service for importing and browsing designs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CaptionLanguages returns the description-language options and the active one.
 * @returns {$CancellablePromise<$models.CaptionLanguageInfo | null>}
 */
export function CaptionLanguages() {
    return $Call.ByID(325200554).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClassifyAll classifies, in the background, every design that has no caption yet.
 * Vision inference is GPU-bound and run one-at-a-time; progress is emitted per
 * design via classify:* events.
 * @returns {$CancellablePromise<void>}
 */
export function ClassifyAll() {
    return $Call.ByID(3623439748);
}

/**
 * ClassifyDesign classifies a single design on demand and returns it updated.
 * @param {string} id
 * @returns {$CancellablePromise<$models.DesignInfo | null>}
 */
export function ClassifyDesign(id) {
    return $Call.ByID(2113077391, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ClassifyStatus reports whether the vision model is available and how many
 * designs have been classified.
 * @returns {$CancellablePromise<$models.ClassifyStatusInfo | null>}
 */
export function ClassifyStatus() {
    return $Call.ByID(3213568687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CountDesigns returns how many designs match the filter.
 * @param {$models.ListFilter} filter
 * @returns {$CancellablePromise<number>}
 */
export function CountDesigns(filter) {
    return $Call.ByID(2275679549, filter);
}

/**
 * DeleteDesign removes one design (row + thumbnail) from the vault.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDesign(id) {
    return $Call.ByID(246867390, id);
}

/**
 * EjectModels unloads the ML models to free memory. Refuses while classification
 * or folder generation is running (would unload mid-inference).
 * @returns {$CancellablePromise<void>}
 */
export function EjectModels() {
    return $Call.ByID(1846236938);
}

/**
 * ExportCatalog prompts for a destination and writes the whole catalog as a
 * portable .svault bundle (index + thumbnails + original files) in the background.
 * Progress is emitted via export:* events.
 * @returns {$CancellablePromise<void>}
 */
export function ExportCatalog() {
    return $Call.ByID(2357553564);
}

/**
 * Facets returns the catalog-wide facets for the filter sidebar.
 * @returns {$CancellablePromise<$models.FacetInfo | null>}
 */
export function Facets() {
    return $Call.ByID(2572796851).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GenerateFolders asks the LLM (in the background) to propose a folder taxonomy
 * and assigns every classified design to its nearest folder. Emits folders:* events.
 * @param {number} targetCount
 * @returns {$CancellablePromise<void>}
 */
export function GenerateFolders(targetCount) {
    return $Call.ByID(2783784617, targetCount);
}

/**
 * GetDesign returns a single design by id.
 * @param {string} id
 * @returns {$CancellablePromise<$models.DesignInfo | null>}
 */
export function GetDesign(id) {
    return $Call.ByID(3126174655, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ImportCatalog prompts for a .svault bundle and merges it into the catalog in the
 * background (non-destructive upsert; no re-processing). Progress via restore:*.
 * @returns {$CancellablePromise<void>}
 */
export function ImportCatalog() {
    return $Call.ByID(3533944145);
}

/**
 * ImportPaths scans the given files/folders and imports every embroidery file.
 * Parsing + rendering run on a worker pool; persistence and event emission happen
 * on a single collector goroutine (keeping DuckDB writes serialized and progress
 * monotonic). One bad file emits import:error and does not abort the batch.
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function ImportPaths(paths) {
    return $Call.ByID(1912837174, paths);
}

/**
 * ListDesigns returns designs matching the filter. When a search term is present
 * and the vision model is wired, results are ranked by semantic similarity;
 * otherwise the search term is a filename substring filter.
 * @param {$models.ListFilter} filter
 * @returns {$CancellablePromise<$models.DesignInfo[]>}
 */
export function ListDesigns(filter) {
    return $Call.ByID(87632774, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListFolders returns the current LLM-generated virtual folders with counts.
 * @returns {$CancellablePromise<$models.FolderInfo[]>}
 */
export function ListFolders() {
    return $Call.ByID(2026409948).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * PickFiles opens a native multi-file dialog and returns the selected paths.
 * @returns {$CancellablePromise<string[]>}
 */
export function PickFiles() {
    return $Call.ByID(936146497).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * PickFolder opens a native folder dialog and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(1191992382);
}

/**
 * SetCaptionLanguage sets the description language by code (e.g. "pt"); it takes
 * effect on the next classification.
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function SetCaptionLanguage(code) {
    return $Call.ByID(298730175, code);
}

/**
 * SetVisionModel selects a model by preset id (loads on next classification).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetVisionModel(id) {
    return $Call.ByID(3100880586, id);
}

/**
 * StopClassify cancels a running batch classification (no-op if none is running).
 * @returns {$CancellablePromise<void>}
 */
export function StopClassify() {
    return $Call.ByID(3654702605);
}

/**
 * VisionModels returns the model picker options and the active one.
 * @returns {$CancellablePromise<$models.VisionModelInfo | null>}
 */
export function VisionModels() {
    return $Call.ByID(2668989021).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CaptionLanguageInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DesignInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ClassifyStatusInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.FacetInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType2);
const $$createType9 = $models.FolderInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $models.VisionModelInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
