// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClassifyCompleteEvent is emitted when the classification batch finishes.
 */
export class ClassifyCompleteEvent {
    /**
     * Creates a new ClassifyCompleteEvent instance.
     * @param {Partial<ClassifyCompleteEvent>} [$$source = {}] - The source object to create the ClassifyCompleteEvent.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("classified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classified"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassifyCompleteEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassifyCompleteEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClassifyCompleteEvent(/** @type {Partial<ClassifyCompleteEvent>} */($$parsedSource));
    }
}

/**
 * ClassifyErrorEvent is emitted when one design fails to classify.
 */
export class ClassifyErrorEvent {
    /**
     * Creates a new ClassifyErrorEvent instance.
     * @param {Partial<ClassifyErrorEvent>} [$$source = {}] - The source object to create the ClassifyErrorEvent.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassifyErrorEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassifyErrorEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClassifyErrorEvent(/** @type {Partial<ClassifyErrorEvent>} */($$parsedSource));
    }
}

/**
 * ClassifyProgressEvent is emitted as each design is classified.
 */
export class ClassifyProgressEvent {
    /**
     * Creates a new ClassifyProgressEvent instance.
     * @param {Partial<ClassifyProgressEvent>} [$$source = {}] - The source object to create the ClassifyProgressEvent.
     */
    constructor($$source = {}) {
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("designID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["designID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassifyProgressEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassifyProgressEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClassifyProgressEvent(/** @type {Partial<ClassifyProgressEvent>} */($$parsedSource));
    }
}

/**
 * ClassifyStatusInfo reports classification coverage of the catalog.
 */
export class ClassifyStatusInfo {
    /**
     * Creates a new ClassifyStatusInfo instance.
     * @param {Partial<ClassifyStatusInfo>} [$$source = {}] - The source object to create the ClassifyStatusInfo.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("classified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classified"] = 0;
        }
        if (!("loaded" in $$source)) {
            /**
             * models currently in memory (eject available)
             * @member
             * @type {boolean}
             */
            this["loaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassifyStatusInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassifyStatusInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClassifyStatusInfo(/** @type {Partial<ClassifyStatusInfo>} */($$parsedSource));
    }
}

/**
 * ColorInfo is one palette swatch.
 */
export class ColorInfo {
    /**
     * Creates a new ColorInfo instance.
     * @param {Partial<ColorInfo>} [$$source = {}] - The source object to create the ColorInfo.
     */
    constructor($$source = {}) {
        if (!("r" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["b"] = 0;
        }
        if (!("hex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hex"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorInfo(/** @type {Partial<ColorInfo>} */($$parsedSource));
    }
}

/**
 * DesignInfo is the JSON-serialisable view of a catalogued design.
 */
export class DesignInfo {
    /**
     * Creates a new DesignInfo instance.
     * @param {Partial<DesignInfo>} [$$source = {}] - The source object to create the DesignInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("widthMM" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["widthMM"] = 0;
        }
        if (!("heightMM" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heightMM"] = 0;
        }
        if (!("stitchCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stitchCount"] = 0;
        }
        if (!("colorChanges" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["colorChanges"] = 0;
        }
        if (!("colorCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["colorCount"] = 0;
        }
        if (!("palette" in $$source)) {
            /**
             * @member
             * @type {ColorInfo[]}
             */
            this["palette"] = [];
        }
        if (!("thumbnailURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thumbnailURL"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("caption" in $$source)) {
            /**
             * Phase 2 (empty until classification runs).
             * @member
             * @type {string}
             */
            this["caption"] = "";
        }
        if (!("style" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["style"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("virtualFolderID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virtualFolderID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesignInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesignInfo}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType1;
        const $$createField15_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("palette" in $$parsedSource) {
            $$parsedSource["palette"] = $$createField9_0($$parsedSource["palette"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField15_0($$parsedSource["tags"]);
        }
        return new DesignInfo(/** @type {Partial<DesignInfo>} */($$parsedSource));
    }
}

/**
 * FacetCountInfo is one facet value and its count.
 */
export class FacetCountInfo {
    /**
     * Creates a new FacetCountInfo instance.
     * @param {Partial<FacetCountInfo>} [$$source = {}] - The source object to create the FacetCountInfo.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetCountInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacetCountInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetCountInfo(/** @type {Partial<FacetCountInfo>} */($$parsedSource));
    }
}

/**
 * FacetInfo drives the filter sidebar.
 */
export class FacetInfo {
    /**
     * Creates a new FacetInfo instance.
     * @param {Partial<FacetInfo>} [$$source = {}] - The source object to create the FacetInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("formats" in $$source)) {
            /**
             * @member
             * @type {FacetCountInfo[]}
             */
            this["formats"] = [];
        }
        if (!("maxSizeMM" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxSizeMM"] = 0;
        }
        if (!("maxStitches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxStitches"] = 0;
        }
        if (!("maxColors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxColors"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacetInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField1_0($$parsedSource["formats"]);
        }
        return new FacetInfo(/** @type {Partial<FacetInfo>} */($$parsedSource));
    }
}

/**
 * FolderInfo is the JSON view of an LLM-generated virtual folder.
 */
export class FolderInfo {
    /**
     * Creates a new FolderInfo instance.
     * @param {Partial<FolderInfo>} [$$source = {}] - The source object to create the FolderInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentID"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderInfo(/** @type {Partial<FolderInfo>} */($$parsedSource));
    }
}

/**
 * FoldersCompleteEvent is emitted when folder generation finishes.
 */
export class FoldersCompleteEvent {
    /**
     * Creates a new FoldersCompleteEvent instance.
     * @param {Partial<FoldersCompleteEvent>} [$$source = {}] - The source object to create the FoldersCompleteEvent.
     */
    constructor($$source = {}) {
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FoldersCompleteEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FoldersCompleteEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FoldersCompleteEvent(/** @type {Partial<FoldersCompleteEvent>} */($$parsedSource));
    }
}

/**
 * FoldersErrorEvent is emitted when folder generation fails.
 */
export class FoldersErrorEvent {
    /**
     * Creates a new FoldersErrorEvent instance.
     * @param {Partial<FoldersErrorEvent>} [$$source = {}] - The source object to create the FoldersErrorEvent.
     */
    constructor($$source = {}) {
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FoldersErrorEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FoldersErrorEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FoldersErrorEvent(/** @type {Partial<FoldersErrorEvent>} */($$parsedSource));
    }
}

/**
 * ImportCompleteEvent is emitted once the whole batch has been processed.
 */
export class ImportCompleteEvent {
    /**
     * Creates a new ImportCompleteEvent instance.
     * @param {Partial<ImportCompleteEvent>} [$$source = {}] - The source object to create the ImportCompleteEvent.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("imported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["imported"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportCompleteEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportCompleteEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportCompleteEvent(/** @type {Partial<ImportCompleteEvent>} */($$parsedSource));
    }
}

/**
 * ImportErrorEvent is emitted when one file fails (the batch continues).
 */
export class ImportErrorEvent {
    /**
     * Creates a new ImportErrorEvent instance.
     * @param {Partial<ImportErrorEvent>} [$$source = {}] - The source object to create the ImportErrorEvent.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportErrorEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportErrorEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportErrorEvent(/** @type {Partial<ImportErrorEvent>} */($$parsedSource));
    }
}

/**
 * ImportProgressEvent is emitted as each file finishes importing (or fails).
 */
export class ImportProgressEvent {
    /**
     * Creates a new ImportProgressEvent instance.
     * @param {Partial<ImportProgressEvent>} [$$source = {}] - The source object to create the ImportProgressEvent.
     */
    constructor($$source = {}) {
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("designID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["designID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportProgressEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportProgressEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportProgressEvent(/** @type {Partial<ImportProgressEvent>} */($$parsedSource));
    }
}

/**
 * ListFilter is the JSON-serialisable filter the gallery sends.
 */
export class ListFilter {
    /**
     * Creates a new ListFilter instance.
     * @param {Partial<ListFilter>} [$$source = {}] - The source object to create the ListFilter.
     */
    constructor($$source = {}) {
        if (!("formats" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["formats"] = [];
        }
        if (!("minSizeMM" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minSizeMM"] = 0;
        }
        if (!("maxSizeMM" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxSizeMM"] = 0;
        }
        if (!("minStitches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minStitches"] = 0;
        }
        if (!("maxStitches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxStitches"] = 0;
        }
        if (!("minColors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minColors"] = 0;
        }
        if (!("maxColors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxColors"] = 0;
        }
        if (!("search" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["search"] = "";
        }
        if (!("virtualFolderID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virtualFolderID"] = "";
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListFilter}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField0_0($$parsedSource["formats"]);
        }
        return new ListFilter(/** @type {Partial<ListFilter>} */($$parsedSource));
    }
}

/**
 * VisionModelInfo is the picker state: the options and which is active.
 */
export class VisionModelInfo {
    /**
     * Creates a new VisionModelInfo instance.
     * @param {Partial<VisionModelInfo>} [$$source = {}] - The source object to create the VisionModelInfo.
     */
    constructor($$source = {}) {
        if (!("currentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentID"] = "";
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {VisionModelOption[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisionModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VisionModelInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        return new VisionModelInfo(/** @type {Partial<VisionModelInfo>} */($$parsedSource));
    }
}

/**
 * VisionModelOption is one selectable model in the UI picker.
 */
export class VisionModelOption {
    /**
     * Creates a new VisionModelOption instance.
     * @param {Partial<VisionModelOption>} [$$source = {}] - The source object to create the VisionModelOption.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisionModelOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VisionModelOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VisionModelOption(/** @type {Partial<VisionModelOption>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ColorInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = FacetCountInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = VisionModelOption.createFrom;
const $$createType6 = $Create.Array($$createType5);
