// Code generated by MockGen. DO NOT EDIT.
// Source: engine.go
//
// Generated by this command:
//
//	mockgen -source=engine.go -destination=mocks/engine.go -package=enginemock_test
//

// Package enginemock_test is a generated GoMock package.
package enginemock_test

import (
	enginebus "stitchvault/internal/business/enginebus"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddDocumentChunk mocks base method.
func (m *MockStore) AddDocumentChunk(ctx context.Context, documentID uuid.UUID, fileName string, startLine int, chunk string, vec enginebus.Vector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDocumentChunk", ctx, documentID, fileName, startLine, chunk, vec)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDocumentChunk indicates an expected call of AddDocumentChunk.
func (mr *MockStoreMockRecorder) AddDocumentChunk(ctx, documentID, fileName, startLine, chunk, vec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDocumentChunk", reflect.TypeOf((*MockStore)(nil).AddDocumentChunk), ctx, documentID, fileName, startLine, chunk, vec)
}

// CreateDocument mocks base method.
func (m *MockStore) CreateDocument(ctx context.Context, doc enginebus.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDocument", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDocument indicates an expected call of CreateDocument.
func (mr *MockStoreMockRecorder) CreateDocument(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDocument", reflect.TypeOf((*MockStore)(nil).CreateDocument), ctx, doc)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, session enginebus.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, session)
}

// DeleteSession mocks base method.
func (m *MockStore) DeleteSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStoreMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStore)(nil).DeleteSession), ctx, sessionID)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(ctx context.Context, sessionID uuid.UUID) (enginebus.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(enginebus.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), ctx, sessionID)
}

// ListSessions mocks base method.
func (m *MockStore) ListSessions(ctx context.Context) ([]enginebus.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx)
	ret0, _ := ret[0].([]enginebus.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockStoreMockRecorder) ListSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockStore)(nil).ListSessions), ctx)
}

// ListDocuments mocks base method.
func (m *MockStore) ListDocuments(ctx context.Context, sessionID uuid.UUID) ([]enginebus.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDocuments", ctx, sessionID)
	ret0, _ := ret[0].([]enginebus.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDocuments indicates an expected call of ListDocuments.
func (mr *MockStoreMockRecorder) ListDocuments(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDocuments", reflect.TypeOf((*MockStore)(nil).ListDocuments), ctx, sessionID)
}

// SearchDocuments mocks base method.
func (m *MockStore) SearchDocuments(ctx context.Context, sessionID uuid.UUID, queryVec []float32, topK int, similarityThreshold float32) ([]enginebus.Fragment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDocuments", ctx, sessionID, queryVec, topK, similarityThreshold)
	ret0, _ := ret[0].([]enginebus.Fragment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDocuments indicates an expected call of SearchDocuments.
func (mr *MockStoreMockRecorder) SearchDocuments(ctx, sessionID, queryVec, topK, similarityThreshold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDocuments", reflect.TypeOf((*MockStore)(nil).SearchDocuments), ctx, sessionID, queryVec, topK, similarityThreshold)
}

// UpdateDocument mocks base method.
func (m *MockStore) UpdateDocument(ctx context.Context, doc enginebus.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDocument", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDocument indicates an expected call of UpdateDocument.
func (mr *MockStoreMockRecorder) UpdateDocument(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDocument", reflect.TypeOf((*MockStore)(nil).UpdateDocument), ctx, doc)
}

// UpdateSession mocks base method.
func (m *MockStore) UpdateSession(ctx context.Context, session enginebus.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockStoreMockRecorder) UpdateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockStore)(nil).UpdateSession), ctx, session)
}
