// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IndexService is the Wails-facing service for session and ingestion management.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../internal/session/models.js";

/**
 * CreateSession creates and persists a new named session.
 * @param {string} name
 * @returns {$CancellablePromise<session$0.Session | null>}
 */
export function CreateSession(name) {
    return $Call.ByID(1189593107, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteSession removes a session from memory and disk.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(id) {
    return $Call.ByID(2748753290, id);
}

/**
 * GetSession returns a single session by ID.
 * @param {string} id
 * @returns {$CancellablePromise<session$0.Session | null>}
 */
export function GetSession(id) {
    return $Call.ByID(2138721437, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * IndexPaths triggers ingestion of the given paths into the session (async).
 * @param {string} sessionID
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function IndexPaths(sessionID, paths) {
    return $Call.ByID(2481782185, sessionID, paths);
}

/**
 * ListSessions returns all in-memory sessions.
 * @returns {$CancellablePromise<(session$0.Session | null)[]>}
 */
export function ListSessions() {
    return $Call.ByID(425874660).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * LoadAll restores persisted sessions into memory. Call once at startup.
 * @returns {$CancellablePromise<void>}
 */
export function LoadAll() {
    return $Call.ByID(3186125932);
}

/**
 * PickDisk opens a native dialog for selecting a mount point (treated as a folder).
 * @returns {$CancellablePromise<string>}
 */
export function PickDisk() {
    return $Call.ByID(3632934521);
}

/**
 * PickFiles opens a native multi-file dialog and returns selected paths.
 * @returns {$CancellablePromise<string[]>}
 */
export function PickFiles() {
    return $Call.ByID(4149369939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PickFolder opens a native folder dialog and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(530372400);
}

// Private type creation functions
const $$createType0 = session$0.Session.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
