// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChatCitationEvent carries source citations once retrieval is done.
 */
export class ChatCitationEvent {
    /**
     * Creates a new ChatCitationEvent instance.
     * @param {Partial<ChatCitationEvent>} [$$source = {}] - The source object to create the ChatCitationEvent.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("citations" in $$source)) {
            /**
             * @member
             * @type {Citation[]}
             */
            this["citations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatCitationEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatCitationEvent}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("citations" in $$parsedSource) {
            $$parsedSource["citations"] = $$createField1_0($$parsedSource["citations"]);
        }
        return new ChatCitationEvent(/** @type {Partial<ChatCitationEvent>} */($$parsedSource));
    }
}

/**
 * ChatDoneEvent signals that streaming has finished.
 */
export class ChatDoneEvent {
    /**
     * Creates a new ChatDoneEvent instance.
     * @param {Partial<ChatDoneEvent>} [$$source = {}] - The source object to create the ChatDoneEvent.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatDoneEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatDoneEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatDoneEvent(/** @type {Partial<ChatDoneEvent>} */($$parsedSource));
    }
}

/**
 * ChatErrorEvent is emitted when the query pipeline fails.
 */
export class ChatErrorEvent {
    /**
     * Creates a new ChatErrorEvent instance.
     * @param {Partial<ChatErrorEvent>} [$$source = {}] - The source object to create the ChatErrorEvent.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatErrorEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatErrorEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatErrorEvent(/** @type {Partial<ChatErrorEvent>} */($$parsedSource));
    }
}

/**
 * ChatTokenEvent carries a streaming token from the model.
 */
export class ChatTokenEvent {
    /**
     * Creates a new ChatTokenEvent instance.
     * @param {Partial<ChatTokenEvent>} [$$source = {}] - The source object to create the ChatTokenEvent.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatTokenEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatTokenEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatTokenEvent(/** @type {Partial<ChatTokenEvent>} */($$parsedSource));
    }
}

/**
 * Citation identifies a source chunk used in a response.
 */
export class Citation {
    /**
     * Creates a new Citation instance.
     * @param {Partial<Citation>} [$$source = {}] - The source object to create the Citation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("documentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentID"] = "";
        }
        if (!("documentName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentName"] = "";
        }
        if (!("chunkIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkIndex"] = 0;
        }
        if (!("excerpt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["excerpt"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Citation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Citation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Citation(/** @type {Partial<Citation>} */($$parsedSource));
    }
}

/**
 * DocumentInfo is the JSON-serialisable view of a document.
 */
export class DocumentInfo {
    /**
     * Creates a new DocumentInfo instance.
     * @param {Partial<DocumentInfo>} [$$source = {}] - The source object to create the DocumentInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content_type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentInfo(/** @type {Partial<DocumentInfo>} */($$parsedSource));
    }
}

/**
 * HistoryMessage is a single chat turn stored per session.
 */
export class HistoryMessage {
    /**
     * Creates a new HistoryMessage instance.
     * @param {Partial<HistoryMessage>} [$$source = {}] - The source object to create the HistoryMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryMessage(/** @type {Partial<HistoryMessage>} */($$parsedSource));
    }
}

/**
 * IndexCompleteEvent is emitted when all documents in a batch finish.
 */
export class IndexCompleteEvent {
    /**
     * Creates a new IndexCompleteEvent instance.
     * @param {Partial<IndexCompleteEvent>} [$$source = {}] - The source object to create the IndexCompleteEvent.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexCompleteEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IndexCompleteEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexCompleteEvent(/** @type {Partial<IndexCompleteEvent>} */($$parsedSource));
    }
}

/**
 * IndexErrorEvent is emitted when a document fails to index.
 */
export class IndexErrorEvent {
    /**
     * Creates a new IndexErrorEvent instance.
     * @param {Partial<IndexErrorEvent>} [$$source = {}] - The source object to create the IndexErrorEvent.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("docName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["docName"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexErrorEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IndexErrorEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexErrorEvent(/** @type {Partial<IndexErrorEvent>} */($$parsedSource));
    }
}

/**
 * IndexProgressEvent is emitted as each document is ingested.
 */
export class IndexProgressEvent {
    /**
     * Creates a new IndexProgressEvent instance.
     * @param {Partial<IndexProgressEvent>} [$$source = {}] - The source object to create the IndexProgressEvent.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("docID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["docID"] = "";
        }
        if (!("docName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["docName"] = "";
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("pct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pct"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexProgressEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IndexProgressEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexProgressEvent(/** @type {Partial<IndexProgressEvent>} */($$parsedSource));
    }
}

/**
 * QueryConfig carries RAG and model parameters from the frontend.
 */
export class QueryConfig {
    /**
     * Creates a new QueryConfig instance.
     * @param {Partial<QueryConfig>} [$$source = {}] - The source object to create the QueryConfig.
     */
    constructor($$source = {}) {
        if (!("topK" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["topK"] = 0;
        }
        if (!("similarityThreshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["similarityThreshold"] = 0;
        }
        if (!("useReranker" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useReranker"] = false;
        }
        if (!("systemPrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemPrompt"] = "";
        }
        if (!("maxTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryConfig(/** @type {Partial<QueryConfig>} */($$parsedSource));
    }
}

/**
 * SessionInfo is the JSON-serialisable view of a session.
 */
export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("documents" in $$source)) {
            /**
             * @member
             * @type {DocumentInfo[]}
             */
            this["documents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField3_0($$parsedSource["documents"]);
        }
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Citation.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DocumentInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
