// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService is the Wails-facing service for RAG-augmented chat.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory clears the chat history for a session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory(sessionID) {
    return $Call.ByID(3456167046, sessionID);
}

/**
 * GetHistory returns the chat history for a session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.HistoryMessage[]>}
 */
export function GetHistory(sessionID) {
    return $Call.ByID(3261598373, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Query performs a RAG-augmented chat turn and streams responses via events.
 * @param {string} sessionID
 * @param {string} userMessage
 * @param {$models.QueryConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function Query(sessionID, userMessage, cfg) {
    return $Call.ByID(2305487471, sessionID, userMessage, cfg);
}

// Private type creation functions
const $$createType0 = $models.HistoryMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
