#!/usr/bin/env python3
"""
gen.py — DEV-ONLY generator for the native Go embroidery reader.

This is NOT part of the app and NOT used at test time. It is run once, by hand, in
the dev venv that has pyembroidery installed, to produce two committed artifacts:

  1. ../threads_gen.go   — the Brother (PEC/PES) and Janome (JEF/SEW) colour charts,
                           emitted verbatim from pyembroidery so the Go reader maps
                           colour indices to the exact same RGB/name as the reference.

  2. <fmt> fixtures + <fmt>.golden.json — one embroidery file per writable common
                           format, written from a canonical pattern, plus the golden
                           output produced by reading it back with pyembroidery (in
                           the same wire shape the old reader.py emitted). The Go
                           differential test (goldens_test.go) reads each fixture and
                           asserts its metrics match the golden — pinning the port to
                           pyembroidery with no Python needed at test time.

Run:  ~/.stitchvault/venv/bin/python testdata/gen.py
"""
import json
import os

import pyembroidery as pe
from pyembroidery.EmbConstant import (
    STITCH, JUMP, TRIM, STOP, END, COLOR_CHANGE, NEEDLE_SET, SEQUIN_EJECT,
    COMMAND_MASK,
)
from pyembroidery.EmbPattern import EmbPattern
from pyembroidery.EmbThreadPec import get_thread_set as pec_threads
from pyembroidery.EmbThreadJef import get_thread_set as jef_threads
from pyembroidery.EmbThreadSew import get_thread_set as sew_threads

HERE = os.path.dirname(os.path.abspath(__file__))

# pyembroidery base command -> StitchVault canonical int (identical to reader.py).
CMD_MAP = {
    STITCH: 0, JUMP: 1, COLOR_CHANGE: 2, NEEDLE_SET: 2,
    TRIM: 3, STOP: 4, END: 5, SEQUIN_EJECT: 6,
}


def go_string(s):
    """A Go double-quoted string literal for an ASCII/BMP string."""
    return json.dumps(s if s is not None else "")


def emit_threads_go():
    charts = [
        ("brotherThreads", pec_threads()),
        ("janomeJefThreads", jef_threads()),
        ("janomeSewThreads", sew_threads()),
    ]
    out = []
    out.append("// Code generated by testdata/gen.py from pyembroidery. DO NOT EDIT.")
    out.append("//")
    out.append("// Brother (PEC/PES) and Janome (JEF/SEW) thread charts. Colour indices in")
    out.append("// those formats reference these tables; the values are copied verbatim from")
    out.append("// pyembroidery so the native reader resolves identical RGB and names.")
    out.append("")
    out.append("package goreader")
    out.append("")
    out.append('import "stitchvault/internal/embroidery"')
    out.append("")
    for name, threads in charts:
        out.append("var %s = []embroidery.Thread{" % name)
        for t in threads:
            # pyembroidery uses None as a placeholder slot; add_thread(None) yields a
            # black EmbThread, so emit one here to keep index alignment.
            if t is None:
                out.append("\t{R: 0x00, G: 0x00, B: 0x00},")
                continue
            out.append(
                "\t{R: 0x%02x, G: 0x%02x, B: 0x%02x, Description: %s, Catalog: %s, Brand: %s},"
                % (
                    t.get_red(), t.get_green(), t.get_blue(),
                    go_string(t.description),
                    go_string(t.catalog_number),
                    go_string(t.brand),
                )
            )
        out.append("}")
        out.append("")
    path = os.path.join(HERE, "..", "threads_gen.go")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote", os.path.normpath(path), "(%d charts)" % len(charts))


def canonical_pattern():
    """A small three-colour design. Geometry is unimportant: the test compares the
    Go reader against pyembroidery reading the SAME written bytes, so format-specific
    re-encoding cancels out."""
    p = EmbPattern()
    p.add_thread({"hex": "ff0000", "description": "Test Red", "brand": "TestBrand", "catalog": "TR"})
    p.add_thread({"hex": "00aa00", "description": "Test Green", "brand": "TestBrand", "catalog": "TG"})
    p.add_thread({"hex": "0000ff", "description": "Test Blue", "brand": "TestBrand", "catalog": "TB"})

    # Block A: zigzag band, x 0..300, y 0/80 (1/10 mm units).
    flip = False
    for x in range(0, 320, 20):
        p.stitch_abs(x, 80 if flip else 0)
        flip = not flip
    p.color_change()
    # Block B: stepped column near x 300..340, y 0..200.
    for i, y in enumerate(range(0, 220, 20)):
        p.stitch_abs(300 + (40 if i % 2 else 0), y)
    p.color_change()
    # Block C: diagonal, x 0..200, y 100..300.
    for k in range(0, 11):
        p.stitch_abs(k * 20, 100 + k * 20)
    p.end()
    return p


def wire(pattern, ext):
    stitches = []
    for s in pattern.stitches:
        base = int(s[2]) & COMMAND_MASK
        stitches.append([s[0] / 10.0, s[1] / 10.0, CMD_MAP.get(base, 0)])
    threads = []
    for t in pattern.threadlist:
        threads.append({
            "r": t.get_red(), "g": t.get_green(), "b": t.get_blue(),
            "description": t.description or "",
            "brand": t.brand or "",
            "catalog": t.catalog_number or "",
        })
    return {"format": ext, "stitches": stitches, "threads": threads}


# Writable common formats (SEW has no pyembroidery writer, so it gets no fixture).
FIXTURE_FORMATS = ["dst", "pes", "pec", "exp", "jef", "vp3", "xxx", "u01"]


def emit_fixtures():
    for ext in FIXTURE_FORMATS:
        p = canonical_pattern()
        fixture = os.path.join(HERE, "canonical.%s" % ext)
        p.write(fixture)
        readback = pe.read(fixture)
        golden = wire(readback, "." + ext)
        with open(fixture + ".golden.json", "w") as f:
            json.dump(golden, f, indent=0)
        print("wrote canonical.%s (+golden, %d stitches, %d threads)"
              % (ext, len(golden["stitches"]), len(golden["threads"])))


if __name__ == "__main__":
    emit_threads_go()
    emit_fixtures()
